# Generated by Django 4.2.3 on 2023-08-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isMember',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(default=1, max_length=223),
            preserve_default=False,
        ),
    ]
