# Generated by Django 4.2.3 on 2023-08-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_ismember_review_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
